export enum Errors {
    JOKER_SKIP_QUESTION_ALREADY_USED = "JOKER_SKIP_QUESTION_ALREADY_USED",
    JOKER_FIFTY_FIFTY_WRONG_TYPE = "JOKER_FIFTY_FIFTY_WRONG_TYPE",
    JOKER_FIFTY_FIFTY_ALREADY_USED = "JOKER_FIFTY_FIFTY_ALREADY_USED",
}